
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 30 18:53:59 CST 2020
//----------------------------------------------------

package konquest.cup.Online;

import java_cup.runtime.Symbol;
import java.util.ArrayList;
import konquest.Replay.Objetos.EnvioReplay;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Mon Mar 30 18:53:59 CST 2020
  */
public class AnalizadorSintacticoOnline extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public AnalizadorSintacticoOnline() {super();}

  /** Constructor which sets the default scanner. */
  public AnalizadorSintacticoOnline(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public AnalizadorSintacticoOnline(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\012\000\002\002\004\000\002\002\005\000\002\002" +
    "\004\000\002\003\007\000\002\003\005\000\002\004\005" +
    "\000\002\004\003\000\002\005\005\000\002\005\005\000" +
    "\002\005\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\030\000\004\007\005\001\002\000\004\002\032\001" +
    "\002\000\006\007\010\010\007\001\002\000\004\010\031" +
    "\001\002\000\004\002\uffff\001\002\000\010\004\013\005" +
    "\012\006\014\001\002\000\006\010\ufffb\012\027\001\002" +
    "\000\004\011\025\001\002\000\004\011\023\001\002\000" +
    "\004\011\021\001\002\000\004\010\016\001\002\000\006" +
    "\010\ufffd\012\017\001\002\000\004\007\010\001\002\000" +
    "\004\010\ufffe\001\002\000\004\013\022\001\002\000\006" +
    "\010\ufff8\012\ufff8\001\002\000\004\014\024\001\002\000" +
    "\006\010\ufffa\012\ufffa\001\002\000\004\014\026\001\002" +
    "\000\006\010\ufff9\012\ufff9\001\002\000\010\004\013\005" +
    "\012\006\014\001\002\000\004\010\ufffc\001\002\000\004" +
    "\002\000\001\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\030\000\004\002\003\001\001\000\002\001\001\000" +
    "\004\003\005\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\004\014\005\010\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\003\017\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\004\027\005\010\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$AnalizadorSintacticoOnline$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$AnalizadorSintacticoOnline$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$AnalizadorSintacticoOnline$do_action(act_num, parser, stack, top,this);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    private ArrayList<EnvioReplay> enviosReplay= new ArrayList<>();
    
    public void setEnvios(ArrayList<EnvioReplay> en){
        this.enviosReplay =en;
    }
public ArrayList<EnvioReplay> getEnvios(){
    if (enviosReplay==null) {
        return new ArrayList<>();
    }
    return enviosReplay;
}

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$AnalizadorSintacticoOnline$actions {


private Object[] atributosRonda = new Object[3];
private ArrayList<EnvioReplay> envios=new ArrayList<>();
private void resetearAtributosRondas(){
        for(int i=0;i<atributosRonda.length;i++){
            atributosRonda[i]=null;
        }
    }


  private final AnalizadorSintacticoOnline parser;

  /** Constructor */
  CUP$AnalizadorSintacticoOnline$actions(AnalizadorSintacticoOnline parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$AnalizadorSintacticoOnline$do_action(
    int                        CUP$AnalizadorSintacticoOnline$act_num,
    java_cup.runtime.lr_parser CUP$AnalizadorSintacticoOnline$parser,
    java.util.Stack            CUP$AnalizadorSintacticoOnline$stack,
    int                        CUP$AnalizadorSintacticoOnline$top,AnalizadorSintacticoOnline aso)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$AnalizadorSintacticoOnline$result;

      /* select the action based on the action number */
      switch (CUP$AnalizadorSintacticoOnline$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // AtributoEnvio ::= NAVES DOS_PUNTOS ENTERO 
            {
              Object RESULT =null;
		int numeroleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoOnline$stack.peek()).left;
		int numeroright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoOnline$stack.peek()).right;
		Object numero = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoOnline$stack.peek()).value;
		atributosRonda[2]=Integer.valueOf((String)numero);
              CUP$AnalizadorSintacticoOnline$result = parser.getSymbolFactory().newSymbol("AtributoEnvio",3, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoOnline$stack.elementAt(CUP$AnalizadorSintacticoOnline$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoOnline$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintacticoOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // AtributoEnvio ::= DESTINO DOS_PUNTOS ID_NOMBRE 
            {
              Object RESULT =null;
		int nombreleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoOnline$stack.peek()).left;
		int nombreright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoOnline$stack.peek()).right;
		String nombre = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoOnline$stack.peek()).value;
		atributosRonda[1]=(String)nombre;
              CUP$AnalizadorSintacticoOnline$result = parser.getSymbolFactory().newSymbol("AtributoEnvio",3, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoOnline$stack.elementAt(CUP$AnalizadorSintacticoOnline$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoOnline$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintacticoOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // AtributoEnvio ::= ORIGEN DOS_PUNTOS ID_NOMBRE 
            {
              Object RESULT =null;
		int nombreleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoOnline$stack.peek()).left;
		int nombreright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoOnline$stack.peek()).right;
		String nombre = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoOnline$stack.peek()).value;
		atributosRonda[0]=(String)nombre;
              CUP$AnalizadorSintacticoOnline$result = parser.getSymbolFactory().newSymbol("AtributoEnvio",3, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoOnline$stack.elementAt(CUP$AnalizadorSintacticoOnline$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoOnline$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintacticoOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // Envio ::= AtributoEnvio 
            {
              Object RESULT =null;
		EnvioReplay pi=new EnvioReplay(atributosRonda);
                                                            resetearAtributosRondas();
                                                             RESULT =pi;
              CUP$AnalizadorSintacticoOnline$result = parser.getSymbolFactory().newSymbol("Envio",2, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoOnline$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoOnline$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintacticoOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // Envio ::= AtributoEnvio COMA Envio 
            {
              Object RESULT =null;
		int releft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoOnline$stack.peek()).left;
		int reright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoOnline$stack.peek()).right;
		Object re = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoOnline$stack.peek()).value;
		RESULT =re;
              CUP$AnalizadorSintacticoOnline$result = parser.getSymbolFactory().newSymbol("Envio",2, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoOnline$stack.elementAt(CUP$AnalizadorSintacticoOnline$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoOnline$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintacticoOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // Envios ::= LLAVE_A Envio LLAVE_C 
            {
              Object RESULT =null;
		int envleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoOnline$stack.elementAt(CUP$AnalizadorSintacticoOnline$top-1)).left;
		int envright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoOnline$stack.elementAt(CUP$AnalizadorSintacticoOnline$top-1)).right;
		Object env = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoOnline$stack.elementAt(CUP$AnalizadorSintacticoOnline$top-1)).value;
		envios.add((EnvioReplay)env);
              CUP$AnalizadorSintacticoOnline$result = parser.getSymbolFactory().newSymbol("Envios",1, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoOnline$stack.elementAt(CUP$AnalizadorSintacticoOnline$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoOnline$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintacticoOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // Envios ::= LLAVE_A Envio LLAVE_C COMA Envios 
            {
              Object RESULT =null;
		int envleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoOnline$stack.elementAt(CUP$AnalizadorSintacticoOnline$top-3)).left;
		int envright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoOnline$stack.elementAt(CUP$AnalizadorSintacticoOnline$top-3)).right;
		Object env = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoOnline$stack.elementAt(CUP$AnalizadorSintacticoOnline$top-3)).value;
		envios.add((EnvioReplay)env);
              CUP$AnalizadorSintacticoOnline$result = parser.getSymbolFactory().newSymbol("Envios",1, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoOnline$stack.elementAt(CUP$AnalizadorSintacticoOnline$top-4)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoOnline$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintacticoOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // Inicio ::= LLAVE_A LLAVE_C 
            {
              Object RESULT =null;

              CUP$AnalizadorSintacticoOnline$result = parser.getSymbolFactory().newSymbol("Inicio",0, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoOnline$stack.elementAt(CUP$AnalizadorSintacticoOnline$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoOnline$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintacticoOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // Inicio ::= LLAVE_A Envios LLAVE_C 
            {
              Object RESULT =null;
		aso.setEnvios(envios);
              CUP$AnalizadorSintacticoOnline$result = parser.getSymbolFactory().newSymbol("Inicio",0, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoOnline$stack.elementAt(CUP$AnalizadorSintacticoOnline$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoOnline$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintacticoOnline$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= Inicio EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoOnline$stack.elementAt(CUP$AnalizadorSintacticoOnline$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoOnline$stack.elementAt(CUP$AnalizadorSintacticoOnline$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoOnline$stack.elementAt(CUP$AnalizadorSintacticoOnline$top-1)).value;
		RESULT = start_val;
              CUP$AnalizadorSintacticoOnline$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoOnline$stack.elementAt(CUP$AnalizadorSintacticoOnline$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoOnline$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$AnalizadorSintacticoOnline$parser.done_parsing();
          return CUP$AnalizadorSintacticoOnline$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

