
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 30 18:53:59 CST 2020
//----------------------------------------------------

package konquest.cup.Online;

/** CUP generated class containing symbol constants. */
public class SimbolosOnline {
  /* terminals */
  public static final int COMA = 8;
  public static final int ORIGEN = 2;
  public static final int DESTINO = 3;
  public static final int ENTERO = 9;
  public static final int NAVES = 4;
  public static final int ERROR = 11;
  public static final int EOF = 0;
  public static final int LLAVE_C = 6;
  public static final int LLAVE_A = 5;
  public static final int error = 1;
  public static final int ID_NOMBRE = 10;
  public static final int DOS_PUNTOS = 7;
}

