
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Mar 29 13:29:54 CST 2020
//----------------------------------------------------

package konquest.cup.Replay;

/** CUP generated class containing symbol constants. */
public class SimbolosReplay {
  /* terminals */
  public static final int PORCENTAJE_MUERTES = 8;
  public static final int PLANETAS = 2;
  public static final int NOMBRE_JUGADOR = 25;
  public static final int COLUMNA = 11;
  public static final int DUE = 4;
  public static final int NAVES = 5;
  public static final int ORIGEN = 12;
  public static final int DECIMAL = 23;
  public static final int RONDAS = 3;
  public static final int ERROR = 26;
  public static final int FILA = 10;
  public static final int TRUE = 14;
  public static final int DOS_PUNTOS = 18;
  public static final int ID_NOMBRE = 24;
  public static final int COMA = 19;
  public static final int NOMBRE = 6;
  public static final int EOF = 0;
  public static final int FALSE = 15;
  public static final int error = 1;
  public static final int LLAVE_C = 17;
  public static final int LLAVE_A = 16;
  public static final int ENTERO = 22;
  public static final int DESTINO = 13;
  public static final int CORCHETE_C = 21;
  public static final int CORCHETE_A = 20;
  public static final int TERMINADO = 9;
  public static final int PRODUCCION = 7;
}

