/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package konquest.ui;

import java.util.ArrayList;
import javax.swing.event.RowSorterEvent;
import konquest.Manejadores.Juego.ControlDeTurnos;
import konquest.Manejadores.Juego.Objetos.EnvioDeFlota;

/**
 *
 * @author sergio
 */
public class FlotasPendientes extends javax.swing.JDialog {
private ControlDeTurnos cdt;
private ArrayList<EnvioDeFlota> envios;
    /**
     * Creates new form FlotasPendientes
     */
    public FlotasPendientes(java.awt.Frame parent, boolean modal,ControlDeTurnos cdt) {
        super(parent, modal);
        this.cdt=cdt;
        initComponents();
        pedirEnvios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sroll = new javax.swing.JScrollPane();
        tblFlotas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Flotas Pendientes");
        setType(java.awt.Window.Type.UTILITY);

        tblFlotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Origen", "Destino", "Naves", "Porcentaje", "Ronda De Llegada", "-"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sroll.setViewportView(tblFlotas);
        if (tblFlotas.getColumnModel().getColumnCount() > 0) {
            tblFlotas.getColumnModel().getColumn(0).setResizable(false);
            tblFlotas.getColumnModel().getColumn(1).setResizable(false);
            tblFlotas.getColumnModel().getColumn(2).setResizable(false);
            tblFlotas.getColumnModel().getColumn(3).setResizable(false);
            tblFlotas.getColumnModel().getColumn(4).setResizable(false);
            tblFlotas.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sroll, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(sroll, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    private void pedirEnvios(){
         envios=new ArrayList<>();
        for (int i = cdt.getCdr().getRondaActual().getNumero(); i >= 1; i--) {
           envios.addAll(cdt.getCdf().obtenerEnviosPorJugador(cdt.getJugadorEnTurnoActual(),i));
        }
        
    }
    private void mostrarEnvios(){
        
        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane sroll;
    private javax.swing.JTable tblFlotas;
    // End of variables declaration//GEN-END:variables
}
