
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Mar 31 12:37:31 CST 2020
//----------------------------------------------------

package konquest.cup.Json;

/** CUP generated class containing symbol constants. */
public class SimbolosJson {
  /* terminals */
  public static final int NUMERO = 30;
  public static final int ACUMULAR = 12;
  public static final int TIPO = 25;
  public static final int NOMBRE = 19;
  public static final int FACIL = 27;
  public static final int PLANETAS = 18;
  public static final int DOS_PUNTOS = 33;
  public static final int CORCHETE_C = 36;
  public static final int NOMBRE_JUGADOR = 38;
  public static final int CORCHETE_A = 35;
  public static final int LLAVE_C = 32;
  public static final int NEUTRALES = 13;
  public static final int LLAVE_A = 31;
  public static final int DIFICIL = 28;
  public static final int MAPA = 2;
  public static final int ID = 3;
  public static final int MOSTRAR_NAVES = 14;
  public static final int EOF = 0;
  public static final int DECIMAL = 29;
  public static final int TRUE = 8;
  public static final int error = 1;
  public static final int COMA = 34;
  public static final int PLANETAS_NEUTRALES = 22;
  public static final int AL_AZAR = 7;
  public static final int ID_MAPA = 39;
  public static final int MOSTRAR_ESTADISTICAS = 15;
  public static final int TAMAÑO = 4;
  public static final int ERROR = 40;
  public static final int PORCENTAJE_MUERTES = 21;
  public static final int HUMANO = 26;
  public static final int PLANETAS_NEUTRALES_MIN = 10;
  public static final int FINALIZACION = 17;
  public static final int PLANETASMIN = 24;
  public static final int MAPA_CIEGO = 11;
  public static final int ID_NOMBRE = 37;
  public static final int JUGADORES = 23;
  public static final int PRODUCCION = 16;
  public static final int COLUMNAS = 6;
  public static final int FALSE = 9;
  public static final int FILAS = 5;
  public static final int NAVES = 20;
}

